# Generated by Django 4.2.6 on 2023-10-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField()),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryTotalQuestions', models.IntegerField()),
                ('categoryCompletedQuestions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentPath', models.CharField(max_length=255)),
                ('contentHeading', models.CharField(max_length=255)),
                ('contentSubHeading', models.CharField(blank=True, max_length=255)),
                ('contentUserNotes', models.TextField(blank=True)),
                ('contentTotalQuestions', models.IntegerField()),
                ('contentCompletedQuestions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionHeading', models.CharField(max_length=255)),
                ('questionLink', models.CharField(blank=True, max_length=255)),
                ('gfgLink', models.CharField(blank=True, max_length=255)),
                ('leetCodeLink', models.CharField(blank=True, max_length=255)),
                ('youTubeLink', models.CharField(blank=True, max_length=255)),
                ('isDone', models.BooleanField(default=False)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('userNotes', models.TextField(blank=True)),
                ('questionIndex', models.IntegerField()),
                ('questionId', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dsaapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dsaapp.content'),
        ),
    ]
